### ISSUE TITLE
json-schema.org unreachable

### ISSUE THREAD

**Issue by bthomason79** [json-schema-org/json-schema-org.github.io#246]
The json-schema.org site is no longer reachable

**Comment by Relequestual** [comment]
I don't think that's the case: https://downforeveryoneorjustme.com/json-schema.org

**Comment by handrews** [comment]
Yes, this still works for me.  @Relequestual I had no idea that site existed, love it!

Since it is up for that site, and for me, and I'm guessing for @Relequestual , I'm closing this.  Please re-open/re-file should it go down and stay down for multiple people.  Also feel free to ping folks on the slack workspace (you can get the link by searching this repo for "slack" if the actual site is unreachable for you).
