### ISSUE TITLE
http://json-schema.org/draft-04/schema with or without #

### ISSUE THREAD

**Issue by domoritz** [json-schema-org/json-schema-org.github.io#74]
Why do [the docs](http://json-schema.org/example1.html) suggest to use `http://json-schema.org/draft-04/schema#` instead of `http://json-schema.org/draft-04/schema`? Is this so that it's obvious how to use references to parts of that schema?

**Comment by handrews** [comment]
@domoritz thanks for your interest!  Do you mean the trailing # fragment?  I don't think anyone remembers- I tried to change it once but the consensus was that it was best left as is.  Historical precedent set by the original owners of the project (we're, I think, the third group to pick it up, with minor continuity from one group to the next.

I'm going to close this because I don't there's more to say since we already debated changing it once, but if you have a follow-on question do feel free to re open it.
